# Generated by Django 4.2.7 on 2023-11-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_libro_portada_alter_libro_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='año_de_publicacion',
            field=models.DateField(),
        ),
    ]
