# Generated by Django 4.2.7 on 2023-11-10 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_libro_año_de_publicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='año_de_publicacion',
            new_name='anio_de_publicacion',
        ),
    ]
