# Generated by Django 4.2.7 on 2023-11-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_rename_año_de_publicacion_libro_anio_de_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_libros/'),
        ),
    ]
