# Generated by Django 4.2.7 on 2023-11-16 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicio', '0007_alter_libro_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='creador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
