# Generated by Django 4.2.7 on 2023-11-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_apellido_usuario_fecha_de_cumpleanios_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='fecha_de_cumpleanios',
            new_name='fecha_de_nacimiento',
        ),
    ]
